{% set name = "pybashify" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pybashify-{{ version }}.tar.gz
  sha256: f0f6c419aa7826b2f6558db5fcd46824e4dbc99d10e26ccd2279e7a7e53f1851

build:
  entry_points:
    - bashify = pybashify.cli.main:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - hatchling
    - pip
  run:
    - python >=3.10
    - typer >=0.12.5,<0.13
    - pydantic >=2.0
    - numpy >=2.1.0,<3
    - astor >=0.8.1,<0.9

test:
  imports:
    - pybashify
  commands:
    - pip check
    - bashify --help
  requires:
    - pip

about:
  summary: Use Python to write bash scripts while interop w/ bash
  home: https://pypi.org/project/pybashify/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AmeerArsala
